describe('RetailConnect', () => {
    it('Login or Signup as Supplier', () => {
        cy.visit('https://app.retailconnect.pk/sign-on-phone')
        cy.get('input[placeholder="03001234567"]').type('03217465299')
        cy.get('.main-button').click()
        //cy.get('.selected > .sc-ion-label-md-h',{timeout:10000}).should('be.visible')
    })
    it.skip('Go to Produts', () => {
        cy.visit('https://app.retailconnect.pk/sign-on-phone')
        cy.get('input[placeholder="03001234567"]').type('03217465299')
        cy.get('.main-button').click()
        cy.get('.selected > .sc-ion-label-md-h').should('be.visible')
        cy.contains('All Distributors').click()
        cy.reload()

    })
    it('Add to cart Products', () => {
        cy.visit('https://app.retailconnect.pk/sign-on-phone')
        cy.get('input[placeholder="03001234567"]').type('03217465299')
        cy.get('.main-button').click()
        cy.get('.selected > .sc-ion-label-md-h').should('be.visible')
        cy.url('https://app.retailconnect.pk/category')
        cy.contains('All Distributors').click()
        cy.get(':nth-child(1) > .categories_item > .p-0 > ion-row.md > [size-md="11"]').click()
        cy.contains('A2A TAB 25 MG 20').click()
        cy.get('.d-flex > :nth-child(2)').click()
        cy.get('.d-flex > :nth-child(2)').click()
        cy.get('.d-flex > :nth-child(2)').click()
        cy.get('.d-flex > :nth-child(1)').click()
        cy.contains('Add to cart').click()
        cy.contains('ACROWIL-F SACHET 10\'S').click()
        cy.get('.d-flex > :nth-child(2)').click()
        cy.get('.d-flex > :nth-child(2)').click()
        cy.get('.d-flex > :nth-child(1)').click()
        cy.contains('Add to cart').click()
        cy.get(':nth-child(13) > .card > .p-0 > ion-row.md > .ion-text-left > .ion-no-margin').click()
        cy.get('.d-flex > :nth-child(2)').click()
        cy.get('.d-flex > :nth-child(2)').click()
        cy.get('.d-flex > :nth-child(2)').click()
        cy.get('.d-flex > :nth-child(2)').click()
        cy.get('.d-flex > :nth-child(2)').click()
        cy.get('.d-flex > :nth-child(2)').click()
        cy.get('.d-flex > :nth-child(1)').click()
        cy.contains('Add to cart').click()

        // add to cart by searching product
        cy.get('.can-go-back > ion-content.md > .container > :nth-child(1) > :nth-child(1) > .item-interactive > .ng-untouched > .native-input').type('adjkashd')
        cy.focused().clear()
        cy.wait(5000)
        cy.get('.can-go-back > ion-content.md > .container > :nth-child(1) > :nth-child(1) > .item-interactive > .ng-untouched > .native-input').type('accukate')
        cy.get('.ion-text-left').click()
        cy.get('.d-flex > :nth-child(2)').click()
        cy.get('.d-flex > :nth-child(2)').click()
        cy.get('.d-flex > :nth-child(2)').click()
        cy.contains('Add to cart').click()
        cy.get('#notifications-badge').click()
        cy.url('https://app.retailconnect.pk/cart')
        cy.contains('Cart Detail')
        // adding 2 more quantities
        cy.get(':nth-child(2) > .ion-no-margin > ion-text.md > .qty-selector > :nth-child(3)').click()
        cy.get(':nth-child(2) > .ion-no-margin > ion-text.md > .qty-selector > :nth-child(3)').click()
        // removing two quantities
        cy.get(':nth-child(4) > .ion-no-margin > ion-text.md > .qty-selector > :nth-child(1)').click()
        cy.get(':nth-child(4) > .ion-no-margin > ion-text.md > .qty-selector > :nth-child(1)').click()
        // clicking for adding quantity
        cy.get(':nth-child(3) > .ion-no-margin > ion-text.md > .qty-selector > .ion-text-center').click()
        cy.focused().clear()
        cy.get(':nth-child(3) > .ion-no-margin > ion-text.md > .qty-selector > .ion-text-center').type('5')
        // clcik on shop more
        cy.get('[routerlink="/category"] > .ion-color').click()
        // again click on cart icon for checkout
        cy.get('#notifications-badge').click()
        // click on checkout button
        cy.get('ion-grid.md > ion-row.md > :nth-child(2) > .ios').click()
        cy.url('https://app.retailconnect.pk/guest-checkout')
        cy.contains('Shipping Information')

        // input all the fields
        cy.get(':nth-child(2) > .item-interactive > .ng-untouched > .native-input').click()
        cy.focused().clear()
        cy.get(':nth-child(2) > .item-interactive > .ng-untouched > .native-input').type('Multan')
        cy.get(':nth-child(3) > .item-interactive > .ng-untouched > .native-input').click()
        cy.focused().clear()
        cy.get(':nth-child(3) > .item-interactive > .ng-untouched > .native-input').type('DHA')
        cy.get(':nth-child(4) > .item-interactive > .ng-untouched > .native-input').click()
        cy.focused().clear()
        cy.get(':nth-child(4) > .item-interactive > .ng-untouched > .native-input').type('Bosan Road')
        cy.get('.submit-btn').click()
        cy.contains('Retailer Details')
        cy.get('.d-align-c > .md > .ios').click()
        cy.url('https://app.retailconnect.pk/confirm')
        cy.contains('Thank You!')
        cy.get('.main-button').click()
        cy.url('https://app.retailconnect.pk/home')
        cy.contains('All Distributors')
        
    })
    it.skip('Order Histtory', () => {
            cy.visit('https://app.retailconnect.pk/sign-on-phone')
            cy.get('input[placeholder="03001234567"]').type('03217465299')
            cy.get('.main-button').click()
            cy.get('.selected > .sc-ion-label-md-h',{timeout:10000}).should('be.visible')
            cy.get(':nth-child(4) > .sc-ion-label-md-h').first().click()
            cy.get(':nth-child(1) > .p-0').click()
            
    })
})