const { expect } = require("chai")

describe('Product Crud Operation', () => {
    it('Add Product without clicking myself', () => {
        cy.visit('https://app.retailconnect.pk/sign-on-phone')
        cy.get('input[placeholder="03001234567"]').type('923044716072')
        cy.get('.ion-no-padding').click()
        cy.get('.main-button').click()
        cy.url('https://app.retailconnect.pk/order-history')
        cy.wait(3000)
        cy.contains('All Products').then(el => {
            el.click();
            cy.url('https://app.retailconnect.pk/v-products')
            cy.wait(3000)
        })
        cy.contains('Add New Product').click()
        cy.wait(3000)
        cy.contains('Close').click()
        cy.wait(3000)
        cy.contains('Add New Product').click()
        cy.wait(3000)
        cy.get('input[placeholder="(i.e Product Name)"]').type('Sample Product')
        cy.wait(3000)
        cy.get('input[placeholder="(i.e Product Name)"]').clear()
        cy.wait(1000)
        cy.contains('Name is required')
        cy.wait(1000)
        cy.get('input[placeholder="(i.e Product Name)"]').type('Sample Product')
        cy.wait(3000)
        cy.get('input[placeholder="(i.e Manufacturer)"]').type('Sample Manufacturer')
        cy.wait(1000)
        cy.get('input[placeholder="(i.e Manufacturer)"]').clear()
        cy.contains('Manufacturer is required')
        cy.wait(1000)
        cy.get('input[placeholder="(i.e Manufacturer)"]').type('Sample Manufacturer')
        cy.wait(1000)
        cy.contains('Create').click()
        cy.wait(3000)

    })

    it.skip('Add Product by clicking myself', () => {
        cy.visit('https://app.retailconnect.pk/sign-on-phone')
        cy.get('input[placeholder="03001234567"]').type('923044716072')
        cy.get('.ion-no-padding').click()
        cy.get('.main-button').click()
        cy.url('https://app.retailconnect.pk/order-history')
        cy.wait(3000)
        cy.contains('All Products').then(el => {
            el.click();
            cy.url('https://app.retailconnect.pk/v-products')
            cy.wait(3000)
        })
        cy.contains('Add New Product').click()
        cy.wait(3000)
        cy.get('input[placeholder="(i.e Product Name)"]').type('testing one Product')
        cy.wait(3000)
        cy.get('.item-lines-none > .ion-no-padding').click()
        cy.wait(1000)
        cy.get('.item-lines-none > .ion-no-padding').click()
        cy.wait(1000)
        cy.get('input[placeholder="(i.e Manufacturer)"]').type('sssssssssssss')
        cy.wait(1000)
        cy.get('.item-lines-none > .ion-no-padding').click()
        cy.wait(1000)
        cy.contains('Create').click()
        cy.wait(1000)

    })

    it('Search Product', () => {
        cy.visit('https://app.retailconnect.pk/sign-on-phone')
        cy.get('input[placeholder="03001234567"]').type('923044716072')
        cy.get('.ion-no-padding').click()
        cy.get('.main-button').click()
        cy.url('https://app.retailconnect.pk/order-history')
        cy.wait(3000)
        cy.contains('All Products').then(el => {
            el.click();
            cy.url('https://app.retailconnect.pk/v-products')
            cy.wait(3000)
        })
        cy.get('input[placeholder="Search..."]').type('testing one product')
        cy.wait(3000)
        cy.get('.ion-padding > .ng-valid > .searchbar-input-container > .searchbar-clear-button ').click()
        cy.wait(3000)
        cy.get('input[placeholder="Search manufacturer"]').type('Al QAMAR')
        cy.wait(3000)
        cy.get('.manufacturer_list > .item > .ng-untouched').click()


    })
    it.skip('Delete Product', () => {
        cy.visit('https://app.retailconnect.pk/sign-on-phone')
        cy.get('input[placeholder="03001234567"]').type('923044716072')
        cy.get('.ion-no-padding').click()
        cy.get('.main-button').click()
        cy.url('https://app.retailconnect.pk/order-history')
        cy.wait(3000)
        cy.contains('All Products').then(el => {
            el.click();
            cy.url('https://app.retailconnect.pk/v-products')
            cy.wait(3000)
        })
        cy.get('input[placeholder="Search..."]').type('sample Product')
        cy.wait(3000)
        cy.contains('Delete').click()
        cy.wait(3000)
        cy.contains('Cancel').click()
        cy.wait(2000)
        cy.contains('Delete').click()
        cy.wait(3000)
        cy.contains('Okay').then((response) => {
            response.click()
            //cy.contains('Product has been successfully deleted.')
        })


    })

    it.skip('Update Product', () => {
        cy.visit('https://app.retailconnect.pk/sign-on-phone')
        cy.get('input[placeholder="03001234567"]').type('923044716072')
        cy.get('.ion-no-padding').click()
        cy.get('.main-button').click()
        cy.url('https://app.retailconnect.pk/order-history')
        cy.wait(3000)
        cy.contains('All Products').then(el => {
            el.click();
            cy.url('https://app.retailconnect.pk/v-products')
            cy.wait(3000)
        })
        cy.get('input[placeholder="Search..."]').type('sample Product')
        cy.wait(3000)
        cy.contains('Edit').click()
        cy.wait(3000)
        cy.get('input[placeholder="(i.e Product Name)"]').clear()
        cy.wait(1000)
        cy.get('input[placeholder="(i.e Product Name)"]').type('Sample one Product')
        cy.wait(3000)
        cy.get('input[placeholder="(i.e Manufacturer)"]').clear()
        cy.wait(1000)
        cy.get('input[placeholder="(i.e Manufacturer)"]').type('Sample one Manufacturer')
        cy.wait(3000)
        cy.get('.ion-padding-horizontal > .d-align-c > .md > .ios').click()
        cy.wait(3000)
        cy.get('input[placeholder="Search..."]').type('sample one product')
        cy.wait(3000)
        cy.get('.ion-padding > .ng-valid > .searchbar-input-container > .searchbar-clear-button ').click()
        cy.wait(3000)
        cy.get('input[placeholder="Search manufacturer"]').type('sample one Manufacturer')
        cy.wait(3000)
        cy.get('.manufacturer_list > .item > .ng-untouched').click()
    })


    it.skip('Check Order Histtory After Accept and cancel', () => {
        cy.visit('https://app.retailconnect.pk/sign-on-phone')
        cy.get('input[placeholder="03001234567"]').type('03217465299')
        cy.get('.main-button').click()
        cy.get('.selected > .sc-ion-label-md-h', { timeout: 10000 }).should('be.visible')
        cy.get(':nth-child(4) > .sc-ion-label-md-h', { timeout: 10000 }).first().click()

    })
})